spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        highlight_sql: true
        show_sql: true

        connection:
          characterEncoding: utf-8
          useUnicode: true
          CharSet: utf-8
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile

          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_SECRET}
            client-name: kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - account_email
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret: ${JWT_SECRET}

network:
  max-connection: 30
  max-per-route: 10
  timeout:
    connect: 5
    socket: 5

port-one:
  imp-key: ${IMP_KEY}
  imp-secret: ${IMP_SECRET}

#logging:
#  level:
#    org.springframework.security: trace