# local
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${LOCAL_MASTER_URL}
        username: ${LOCAL_MASTER_USERNAME}
        password: ${LOCAL_MASTER_PASSWORD}
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${LOCAL_SLAVE_URL}
        username: ${LOCAL_SLAVE_USERNAME}
        password: ${LOCAL_SLAVE_PASSWORD}

  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        connection:
          characterEncoding: utf-8
          useUnicode: true
          CharSet: utf-8
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
login:
  redirect-url: http://localhost/login-success