# prod
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_MYSQL_URL}
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}

  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        connection:
          characterEncoding: utf-8
          useUnicode: true
          CharSet: utf-8
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://raincatch.site/login/oauth2/code/google
          kakao:
            redirect-uri: http://raincatch.site/login/oauth2/code/kakao
login:
  redirect-url: http://raincatch.site/login-success