name: Shared Backend Pull Request Actions

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'backend/**'

jobs:
  call-reusable-build:
    uses: ./.github/workflows/backend-build.yml
    permissions:
      contents: read