name: Shared Backend Pull Request Actions

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'backend/**'

permissions:
  contents: read

jobs:
  call-reusable-build:
    uses: ./.github/workflows/backend-build.yml