name: Shared Springboot Build Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: BACK_BUILD

    steps:
      - name: Git Clone Repository
        uses: actions/checkout@v4

      - name: Check Secrets Availability
        run: |
          [ ! -z "${{ secrets.GOOGLE_ID }}" ] && echo "GOOGLE_ID is set."
          [ ! -z "${{ secrets.GOOGLE_SECRET }}" ] && echo "GOOGLE_SECRET is set."
          [ ! -z "${{ secrets.KAKAO_ID }}" ] && echo "KAKAO_ID is set."
          [ ! -z "${{ secrets.KAKAO_SECRET }}" ] && echo "KAKAO_SECRET is set."
          [ ! -z "${{ secrets.JWT_SECRET }}" ] && echo "JWT_SECRET is set."
          [ ! -z "${{ secrets.IMP_KEY }}" ] && echo "IMP_KEY is set."
          [ ! -z "${{ secrets.IMP_SECRET }}" ] && echo "IMP_SECRET is set."
        shell: bash
        working-directory: ./backend

      - name: Setup JDK temurin 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.8.0

      - name: Grant execute permission to Gradlew
        run: chmod +x ./gradlew
        working-directory: ./backend

      - name: Build With Gradle
        run: ./gradlew clean build --info
        working-directory: ./backend
        env:
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          KAKAO_ID: ${{ secrets.KAKAO_ID }}
          KAKAO_SECRET: ${{ secrets.KAKAO_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          IMP_KEY: ${{ secrets.IMP_KEY }}
          IMP_SECRET: ${{ secrets.IMP_SECRET }}

      - name: Zip Build File
        if: github.event_name == 'push'
        run: zip -q -r ../backend.zip build/libs scripts appspec.yml
        working-directory: ./backend

      - name: Upload Zip File to Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: backend.zip
          path: backend.zip