name: Shared deploy Workflow

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_BUCKET_TO_DEPLOY:
        required: true
      AWS_CODE_DEPLOY_APP:
        required: true
      AWS_CODE_DEPLOY_GROUP:
        required: true
      AWS_CODE_DEPLOY_CONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEPLOY

    steps:
      - name: Download Zip File to Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.path }}.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Upload to S3
        run: |
          ls -a
          aws s3 cp --region ${{ secrets.AWS_DEFAULT_REGION }} $PATH.zip s3://$AWS_BUCKET_TO_DEPLOY/$PATH/$GITHUB_SHA.zip;
        env:
          AWS_BUCKET_TO_DEPLOY: ${{ secrets.AWS_BUCKET_TO_DEPLOY }}
          PATH: ${{ inputs.path }}

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment
          --application-name $AWS_CODE_DEPLOY_APP
          --deployment-config-name $AWS_CODE_DEPLOY_CONFIG
          --deployment-group-name $AWS_CODE_DEPLOY_GROUP
          --s3-location bucket=$AWS_BUCKET_TO_DEPLOY,bundleType=zip,key=$PATH/$GITHUB_SHA.zip
        env:
          AWS_BUCKET_TO_DEPLOY: ${{ secrets.AWS_BUCKET_TO_DEPLOY }}
          AWS_CODE_DEPLOY_APP: ${{ secrets.AWS_CODE_DEPLOY_APP }}
          AWS_CODE_DEPLOY_CONFIG: ${{ secrets.AWS_CODE_DEPLOY_CONFIG }}
          AWS_CODE_DEPLOY_GROUP: ${{ secrets.AWS_CODE_DEPLOY_GROUP }}
          PATH: ${{ inputs.path }}