name: Shared Frontend Push Actions

on:
  push:
    branches: ["main"]
    paths:
      - 'frontend/**'

jobs:
  call-reusable-build:
    uses: ./.github/workflows/frontend-build.yml
    secrets: inherit
    permissions:
      contents: read

  call-reusable-deploy:
    needs: call-reusable-build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      id-token: write
    with:
      path: 'frontend'