name: Shared Frontend Pull Request Actions

on:
  pull_request:
    branches: ["main"]
    paths:
      - 'frontend/**'

permissions:
  contents: read

jobs:
  call-reusable-build:
    uses: ./.github/workflows/frontend-build.yml
    secrets: inherit